name: PR title verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # tag=v4.1.7

      - name: Check if PR title is valid
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          ./hack/verify-pr-title.sh "${PR_TITLE}"
